import { Heading } from '@chakra-ui/react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import LandingScreen from '../components/landing-screen';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingScreen />
    </div>
  );
}
